### PR TITLE
tests with colors

### PR DESCRIPTION
**Pull request by danielleberre**
Provide GREEN/RED colors when the tests pass or fail.

### CODE REVIEW

**Comment by arminbiere** [comment]
Thanks, but I consider this more as an enhancement request.  Actually your solution ignores the situation (on Travis this was the case once) that the output is connected to a Terminal.  I will at one point copy the code from Kissat for colors, but was too lazy for that.

**Comment by danielleberre** [comment]
I added a test to add the colors only if the script is ran on a terminal. Was that the problem?

**Comment by arminbiere** [comment]
You want to use ' if [ -t 1 ] ' as in 

[https://github.com/arminbiere/cadical/blob/master/scripts/colors.sh](https://github.com/arminbiere/cadical/blob/master/scripts/colors.sh)

**Comment by arminbiere** [comment]
Now I see that you also have a -t 1 test in the script.    In any case I do not do pull request because I am not developping on GitHub but only use it for releases.

**Comment by arminbiere** [comment]
Probably should add a CONTRIBUTING file ...

**Comment by danielleberre** [comment]
Actually, you do not need the else part in your script :)

**Comment by arminbiere** [comment]
Right .... Thanks.

**Pull request closed without merging**
